version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.20.4 # Use your app's Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix $CODEBUILD_SRC_DIR/frontend
  build:
    commands:
      - echo "Building the React app..."
      - npm run build --prefix $CODEBUILD_SRC_DIR/frontend
  post_build:
    commands:
      - echo "Syncing build artifacts to S3..."
      - aws s3 sync frontend/build/ s3://pagebuilder-v1.0.2 --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E22SY9SVEOD43 --paths "/*"

artifacts:
  files:
    - '**/*'
