version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.20.4 # Use your app's Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Syncing build artifacts to S3..."
      - aws s3 sync build/ s3://pagebuilder-v1.0.1 --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E2OZF36WFL3JON --paths "/*"

artifacts:
  files:
    - '**/*'
